sonar.projectKey=coolmate-ecommerce-backend
sonar.projectName=Coolmate E-commerce Backend
sonar.projectVersion=1.0.0

sonar.sources=.
sonar.exclusions=**/*_test.go,**/vendor/**,**/.git/**

sonar.coverage.exclusions=**/*_test.go,**/vendor/**
sonar.go.coverage.reportPaths=coverage.out

sonar.go.tests.reportPaths=test_report.json
sonar.go.golangci-lint.reportPaths=golangci-lint-report.json

sonar.qualitygate.wait=true
